obj-m := ex1_simple_module.o
obj-m += ex2_simple_init.o
obj-m += ex3_simple_exit.o


obj-m := ex1_simple_module.o
obj-m += ex4_simple_module.o

obj-m := ex5_exporting_symbols.o
obj-m += ex5_using_symbols.o

obj-m := ex6_module_param.o
obj-m := ex7_simple_char_drv.o
